AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Number Processor Lambda Function demonstrating inefficient I/O operations during initialization

Resources:
  NumProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          CONFIG_FILE: config.yaml